# ForwardsCoverBot - لا تدع الأشخاص الموجودين على Telegram يعيدون توجيه اسمك على ملصق التوجيه
# حقوق النشر (C) 2017-2022 Dario <dariomsn@hotmail.it> (github.com/91DarioDev)
#
# ForwardsCoverBot هو برنامج مجاني: يمكنك إعادة توزيعه و / أو تعديله
# بموجب شروط رخصة جنو أفيرو العمومية كما تم نشرها
# بواسطة Free Software Foundation ، إما الإصدار 3 من الترخيص ، أو
# (حسب اختيارك) أي إصدار لاحق.
#
يتم توزيع # ForwardsCoverBot على أمل أن يكون مفيدًا ،
# لكن دون أي ضمان ؛ حتى بدون الضمان الضمني لـ
# القابلية للتسويق أو الملاءمة لغرض معين. انظر
# رخصة جنو أفيرو العمومية لمزيد من التفاصيل.
#
# يجب أن تكون قد تلقيت نسخة من رخصة جنو أفيرو العمومية
# مع ForwardsCoverBot. إذا لم يكن كذلك ، راجع <http://www.gnu.org/licenses/>

# ______________________________________________________________________________

# قبل تشغيل الروبوت يجب عليك إنشاء ملف باسم `config.yaml`
# يجب أن يكون الملف هو نفسه هذا ، مع استبدال متغيرات العينة ببيانات حقيقية


# رمز الروبوت الذي تحصل عليه من t.me/botfather (اكتب: str)
bot_token : " 6189234125:AAFjbG62setPOD0kDI3bBayqx8tyCrtGMq4 "

# اسم قاعدة البيانات (نوع: str)
db_path : " https://github.com/91DarioDev/forwardscoverbot
cd forwardscoverbot
pip install . "

# قائمة تحتوي على معرفات برقية لمسؤولي الروبوت (النوع: معرفات int)
المشرفون :
- 1234
